version: '3'
services:
  app:
    build: ./app
    restart: on-failure
    networks:
      - mynetwork
    volumes:
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
      - ./log/uwsgi/:/var/log/uwsgi/
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:12-alpine
    restart: on-failure
    networks:
      - mynetwork
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - mynetwork
    volumes:
      - ./static:/usr/share/nginx/static
      - ./media:/usr/share/nginx/media
      - ./log/nginx/:/var/log/nginx/
    depends_on:
      - app

networks:
  mynetwork:



